#!/usr/bin/perl -w
# ****************************************************************************
# CUI
#
# The Advanced Framework for Simulation, Integration, and Modeling (AFSIM)
#
# The use, dissemination or disclosure of data in this file is subject to
# limitation or restriction. See accompanying README and LICENSE for details.
# ****************************************************************************

# File name: event_filter1.pl
# Version: 05/15/2009

while (<>) { # Read input from STDIN
    if ($_ =~ /SENSOR_TRACK_INITIATED/) {
	print; # If match, print to STDOUT
    }
}

__END__

=pod

=head1 NAME - event_filter1.pl

=head2 SYNOPSIS

perl_filter1.pl - A simple example Perl script to filter single long
line Event file output, such as that generated by Perl script
"ev-combine.pl", to output only those "SENSOR_TRACK_INITIATED" events.

=head2 DESCRIPTION

See "ev-combine.pl" and its documentation for more details.

=head2 AUTHOR

 Gary Richardson
 Strategic Projects & Analysis
 Boeing Research & Technology

=head2 BUGS AND TECHNICAL SUPPORT

If you think you have found a bug in one of our existing data
processing/analysis tools, have ideas on how to improve these
utilities, or simply want help in getting started using the Perl
programming language in your modeling/simulation efforts (including
models other than those developed using AFSIM), please contact us.

 Gary Richardson, Associate Technical Fellow
 Strategic Projects & Analysis
 Boeing Research & Technology
 Tel: 314-232-5451
 E-mail: gary.a.richardson@boeing.com

=head2 COPYRIGHT

Copyright - The Boeing Company, 2009

=cut
