#!/usr/bin/perl -w
# ****************************************************************************
# CUI
#
# The Advanced Framework for Simulation, Integration, and Modeling (AFSIM)
#
# The use, dissemination or disclosure of data in this file is subject to
# limitation or restriction. See accompanying README and LICENSE for details.
# ****************************************************************************

# File name: event_filter2.pl
# Version: 05/15/2009

while (<>) { # Read input from STDIN
    # Save input line to variable "$inline" and remove
    #  Newline character from end-of-line:
    chomp($inline = $_);

    # If Event type included in this line:
    if ($inline =~ /SENSOR_TRACK_INITIATED/) {

	# Make sure there is no trailing whitespace characters to
	#  avoid ending the line with a comma:
	$inline =~ s/\s+$//;

	# Next, replace whitespace between each word with a comma
	$inline =~ s/\s+/\,/g;

	print "$inline\n"; # Print output to STDOUT
    }
}

__END__

=pod

=head1 NAME - event_filter2.pl

=head2 SYNOPSIS

perl_filter2.pl - A simple example Perl script to filter single long
line Event file output, such as that generated by Perl script
"ev-combine.pl", to output only those "SENSOR_TRACK_INITIATED" events.
Also, replace whitespace between each word with a comma to enable
processing with Microsoft "Excel" (Windows environment) or Open Office
"oocalc" (Linux environment). Output file should be saved with a
".csv" file extension.

=head2 DESCRIPTION

See "ev-combine.pl" and its documentation for more details.

=head2 AUTHOR

 Gary Richardson
 Strategic Projects & Analysis
 Boeing Research & Technology

=head2 BUGS AND TECHNICAL SUPPORT

If you think you have found a bug in one of our existing data
processing/analysis tools, have ideas on how to improve these
utilities, or simply want help in getting started using the Perl
programming language in your modeling/simulation efforts (including
models other than those developed using AFSIM), please contact us.

 Gary Richardson, Associate Technical Fellow
 Strategic Projects & Analysis
 Boeing Research & Technology
 Tel: 314-232-5451
 E-mail: gary.a.richardson@boeing.com

=head2 COPYRIGHT

Copyright - The Boeing Company, 2009

=cut
